# Database Configuration
database:
  path: ./storage/db/nepremicninko.sqlite
  auto_flush: true

# Discord Configuration
discord:
  webhook_url: https://discord.com/api/webhooks/...
  notify_on_error: false

# Scheduler Configuration
scheduler:
  enabled: true
  interval_minutes: 3
  timezone: Europe/Ljubljana

# URLs to scrape
urls:
  - url_1
  - url_2
  - ...