services:
  nepremicninko:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: nepremicninko
    restart: unless-stopped
    volumes:
      - ../storage:/app/storage
      - ../logs:/app/logs
      - ../config/:/app/config/
    environment:
      - ENVIRONMENT=production
      - SCHEDULER_ENABLED=true
      - SCHEDULER_INTERVAL_MINUTES=1
    env_file:
      - ../.env