services:
  nepremicninko:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: nepremicninko
    restart: unless-stopped
    volumes:
      - ../storage:/app/storage
      - ../logs:/app/logs
      - ../config.yaml:/app/config.yaml